set(__QT_DEPLOY_TARGET_hyremote-core_FILE F:/workspace/hyremote/HyRemote/build312/core/libhyremote-core.a)
set(__QT_DEPLOY_TARGET_hyremote-core_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_hyremote-remoteaccess_FILE F:/workspace/hyremote/HyRemote/build312/runtime/libHyRemoteRemoteAccess.dll)
set(__QT_DEPLOY_TARGET_hyremote-remoteaccess_TYPE SHARED_LIBRARY)
set(__QT_DEPLOY_TARGET_hyremote-remoteaccess_RUNTIME_DLLS C:/Qt/6.8.3/mingw_64/bin/Qt6Widgets.dll;C:/Qt/6.8.3/mingw_64/bin/Qt6Quick.dll;C:/Qt/6.8.3/mingw_64/bin/Qt6QmlMeta.dll;C:/Qt/6.8.3/mingw_64/bin/Qt6QmlWorkerScript.dll;C:/Qt/6.8.3/mingw_64/bin/Qt6QmlModels.dll;C:/Qt/6.8.3/mingw_64/bin/Qt6Qml.dll;C:/Qt/6.8.3/mingw_64/bin/Qt6Network.dll;C:/Qt/6.8.3/mingw_64/bin/Qt6OpenGL.dll;C:/Qt/6.8.3/mingw_64/bin/Qt6Gui.dll;C:/Qt/6.8.3/mingw_64/bin/Qt6Core.dll)
