cmake_minimum_required(VERSION 3.21)

get_filename_component(HYREMOTE_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

# Built-in defaults are deliberately small. A repository-root build.yml overrides them,
# and explicit command-line options override build.yml for one-off builds.
set(HYB_CONFIG_PATH "${HYREMOTE_SOURCE_DIR}/build.yml")
set(HYB_MODE "qpa")
set(HYB_INTEGRATIONS "")
set(HYB_BUILD_TYPE "Release")
set(HYB_BUILD_DIR "build")
set(HYB_GENERATOR "Ninja")
set(HYB_JOBS "")
set(HYB_QT_PREFIX "")
set(HYB_TOOLCHAIN "")
set(HYB_C_COMPILER "")
set(HYB_CXX_COMPILER "")
set(HYB_TESTS_BUILD "OFF")
set(HYB_TESTS_RUN "OFF")
set(HYB_TESTS_PARALLEL "")
set(HYB_TESTS_EXCLUDE "")
set(HYB_TESTS_XVFB "OFF")
set(HYB_EXAMPLES "ON")
set(HYB_CLEAN "OFF")
set(HYB_VERBOSE "OFF")
set(HYB_PRINT_CONFIG "OFF")
set(HYB_CONFIG_REQUIRED "OFF")
set(HYB_CMAKE_CACHE_ENTRIES "")
set(HYB_ENV_ENTRIES "")

function(hyb_trim_quotes input output)
    string(STRIP "${input}" value)
    if(value MATCHES "^\"(.*)\"$")
        set(value "${CMAKE_MATCH_1}")
    elseif(value MATCHES "^'(.*)'$")
        set(value "${CMAKE_MATCH_1}")
    endif()
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(hyb_bool input output context)
    string(TOLOWER "${input}" value)
    if(value STREQUAL "true" OR value STREQUAL "yes" OR value STREQUAL "on" OR value STREQUAL "1")
        set(${output} "ON" PARENT_SCOPE)
    elseif(value STREQUAL "false" OR value STREQUAL "no" OR value STREQUAL "off" OR value STREQUAL "0")
        set(${output} "OFF" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "${context}: expected boolean, got '${input}'")
    endif()
endfunction()

function(hyb_append_pair variable key value)
    set(list_value "${${variable}}")
    list(APPEND list_value "${key}=${value}")
    set(${variable} "${list_value}" PARENT_SCOPE)
endfunction()

function(hyb_set_entry section key raw_value origin)
    hyb_trim_quotes("${raw_value}" value)
    string(TOLOWER "${section}" section_l)
    string(TOLOWER "${key}" key_l)

    if(section_l STREQUAL "")
        if(key_l STREQUAL "version")
            if(NOT value STREQUAL "1")
                message(FATAL_ERROR "${origin}: unsupported build.yml version '${value}', expected 1")
            endif()
        elseif(key_l STREQUAL "mode")
            set(HYB_MODE "${value}" PARENT_SCOPE)
        elseif(key_l STREQUAL "integrations")
            set(items "${value}")
            string(REGEX REPLACE "^\\[" "" items "${items}")
            string(REGEX REPLACE "\\]$" "" items "${items}")
            string(REPLACE "," ";" items "${items}")
            set(normalized "")
            foreach(item IN LISTS items)
                string(STRIP "${item}" item)
                hyb_trim_quotes("${item}" item)
                if(NOT item STREQUAL "")
                    list(APPEND normalized "${item}")
                endif()
            endforeach()
            set(HYB_INTEGRATIONS "${normalized}" PARENT_SCOPE)
        else()
            message(FATAL_ERROR "${origin}: unsupported top-level key '${key}'")
        endif()
    elseif(section_l STREQUAL "build")
        if(key_l STREQUAL "type")
            set(HYB_BUILD_TYPE "${value}" PARENT_SCOPE)
        elseif(key_l STREQUAL "directory")
            set(HYB_BUILD_DIR "${value}" PARENT_SCOPE)
        elseif(key_l STREQUAL "generator")
            set(HYB_GENERATOR "${value}" PARENT_SCOPE)
        elseif(key_l STREQUAL "jobs")
            if(value STREQUAL "auto" OR value STREQUAL "")
                set(value "")
            elseif(NOT value MATCHES "^[1-9][0-9]*$")
                message(FATAL_ERROR "${origin}: build.jobs must be a positive integer or 'auto'")
            endif()
            set(HYB_JOBS "${value}" PARENT_SCOPE)
        elseif(key_l STREQUAL "examples")
            hyb_bool("${value}" parsed "${origin}: build.examples")
            set(HYB_EXAMPLES "${parsed}" PARENT_SCOPE)
        else()
            message(FATAL_ERROR "${origin}: unsupported build key '${key}'")
        endif()
    elseif(section_l STREQUAL "qt")
        if(key_l STREQUAL "prefix")
            set(HYB_QT_PREFIX "${value}" PARENT_SCOPE)
        else()
            message(FATAL_ERROR "${origin}: unsupported qt key '${key}'")
        endif()
    elseif(section_l STREQUAL "compiler")
        if(key_l STREQUAL "c")
            set(HYB_C_COMPILER "${value}" PARENT_SCOPE)
        elseif(key_l STREQUAL "cxx")
            set(HYB_CXX_COMPILER "${value}" PARENT_SCOPE)
        elseif(key_l STREQUAL "toolchain")
            set(HYB_TOOLCHAIN "${value}" PARENT_SCOPE)
        else()
            message(FATAL_ERROR "${origin}: unsupported compiler key '${key}'")
        endif()
    elseif(section_l STREQUAL "tests")
        if(key_l STREQUAL "build")
            hyb_bool("${value}" parsed "${origin}: tests.build")
            set(HYB_TESTS_BUILD "${parsed}" PARENT_SCOPE)
        elseif(key_l STREQUAL "run")
            hyb_bool("${value}" parsed "${origin}: tests.run")
            set(HYB_TESTS_RUN "${parsed}" PARENT_SCOPE)
        elseif(key_l STREQUAL "parallel")
            if(value STREQUAL "auto" OR value STREQUAL "")
                set(value "")
            elseif(NOT value MATCHES "^[1-9][0-9]*$")
                message(FATAL_ERROR "${origin}: tests.parallel must be a positive integer or 'auto'")
            endif()
            set(HYB_TESTS_PARALLEL "${value}" PARENT_SCOPE)
        elseif(key_l STREQUAL "exclude")
            set(HYB_TESTS_EXCLUDE "${value}" PARENT_SCOPE)
        elseif(key_l STREQUAL "xvfb")
            hyb_bool("${value}" parsed "${origin}: tests.xvfb")
            set(HYB_TESTS_XVFB "${parsed}" PARENT_SCOPE)
        else()
            message(FATAL_ERROR "${origin}: unsupported tests key '${key}'")
        endif()
    elseif(section_l STREQUAL "cmake")
        if(key MATCHES "^(HYREMOTE_BUILD_QML_API|HYREMOTE_WITH_GENERIC_PLUGIN|HYREMOTE_WITH_QPA_PROXY|HYREMOTE_BUILD_TESTS|HYREMOTE_BUILD_EXAMPLES|CMAKE_PREFIX_PATH|CMAKE_TOOLCHAIN_FILE|CMAKE_C_COMPILER|CMAKE_CXX_COMPILER)$")
            message(FATAL_ERROR
                "${origin}: '${key}' has a dedicated build.yml field and may not be duplicated under cmake")
        endif()
        hyb_append_pair(HYB_CMAKE_CACHE_ENTRIES "${key}" "${value}")
        set(HYB_CMAKE_CACHE_ENTRIES "${HYB_CMAKE_CACHE_ENTRIES}" PARENT_SCOPE)
    elseif(section_l STREQUAL "environment")
        hyb_append_pair(HYB_ENV_ENTRIES "${key}" "${value}")
        set(HYB_ENV_ENTRIES "${HYB_ENV_ENTRIES}" PARENT_SCOPE)
    else()
        message(FATAL_ERROR "${origin}: unsupported section '${section}'")
    endif()
endfunction()

# HyRemote intentionally supports a small, deterministic YAML subset rather than acquiring a
# Python/PyYAML dependency just to bootstrap the C++ build. Supported YAML is documented in the
# user guide: scalar top-level values, one-level mappings, and the integrations sequence.
macro(hyb_load_config path)
    if(NOT EXISTS "${path}")
        if(HYB_CONFIG_REQUIRED)
            message(FATAL_ERROR "Build configuration not found: ${path}")
        endif()
        return()
    endif()

    file(STRINGS "${path}" lines ENCODING UTF-8)
    set(section "")
    set(line_number 0)
    foreach(raw_line IN LISTS lines)
        math(EXPR line_number "${line_number}+1")
        set(line "${raw_line}")
        string(REGEX REPLACE "[ \t]+#.*$" "" line "${line}")
        string(STRIP "${line}" stripped)
        if(stripped STREQUAL "" OR stripped MATCHES "^#")
            continue()
        endif()

        string(REGEX MATCH "^[ \t]+" indent_match "${line}")
        if(indent_match STREQUAL "")
            set(indent 0)
        else()
            string(LENGTH "${indent_match}" indent)
        endif()
        set(origin "${path}:${line_number}")

        if(indent EQUAL 0)
            set(section "")
            if(stripped MATCHES "^([A-Za-z0-9_.-]+):[ \t]*(.*)$")
                set(key "${CMAKE_MATCH_1}")
                set(value "${CMAKE_MATCH_2}")
                if(value STREQUAL "")
                    string(TOLOWER "${key}" section)
                    if(NOT section MATCHES "^(build|qt|compiler|tests|cmake|environment|integrations)$")
                        message(FATAL_ERROR "${origin}: unsupported section '${key}'")
                    endif()
                else()
                    hyb_set_entry("" "${key}" "${value}" "${origin}")
                endif()
            else()
                message(FATAL_ERROR "${origin}: expected 'key: value' or a supported section")
            endif()
        else()
            if(section STREQUAL "")
                message(FATAL_ERROR "${origin}: nested value without a parent section")
            endif()
            if(section STREQUAL "integrations")
                if(NOT stripped MATCHES "^-[ \t]+(.+)$")
                    message(FATAL_ERROR "${origin}: integrations must be a YAML list")
                endif()
                hyb_trim_quotes("${CMAKE_MATCH_1}" item)
                list(APPEND HYB_INTEGRATIONS "${item}")
            elseif(stripped MATCHES "^([A-Za-z0-9_.-]+):[ \t]*(.*)$")
                hyb_set_entry("${section}" "${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}" "${origin}")
            else()
                message(FATAL_ERROR "${origin}: expected 'key: value'")
            endif()
        endif()
    endforeach()
endmacro()

function(hyb_collect_args output)
    set(args "")
    set(after_separator OFF)
    math(EXPR last "${CMAKE_ARGC}-1")
    foreach(i RANGE 0 ${last})
        set(value "${CMAKE_ARGV${i}}")
        if(after_separator)
            list(APPEND args "${value}")
        elseif(value STREQUAL "--")
            set(after_separator ON)
        endif()
    endforeach()
    set(${output} "${args}" PARENT_SCOPE)
endfunction()

hyb_collect_args(HYB_ARGS)
list(LENGTH HYB_ARGS argc)

# Pass 1 only selects the configuration file. The selected file is loaded before normal
# command-line parsing so explicit CLI values always win over persisted project defaults.
set(i 0)
while(i LESS argc)
    list(GET HYB_ARGS ${i} arg)
    if(arg MATCHES "^--config=(.+)$")
        set(HYB_CONFIG_PATH "${CMAKE_MATCH_1}")
        set(HYB_CONFIG_REQUIRED ON)
    elseif(arg STREQUAL "--config")
        math(EXPR i "${i}+1")
        if(i GREATER_EQUAL argc)
            message(FATAL_ERROR "--config requires a path")
        endif()
        list(GET HYB_ARGS ${i} HYB_CONFIG_PATH)
        set(HYB_CONFIG_REQUIRED ON)
    elseif(arg STREQUAL "--no-config")
        set(HYB_CONFIG_PATH "")
    endif()
    math(EXPR i "${i}+1")
endwhile()

if(NOT HYB_CONFIG_PATH STREQUAL "")
    if(NOT IS_ABSOLUTE "${HYB_CONFIG_PATH}")
        set(HYB_CONFIG_PATH "${HYREMOTE_SOURCE_DIR}/${HYB_CONFIG_PATH}")
    endif()
    cmake_path(NORMAL_PATH HYB_CONFIG_PATH)
    hyb_load_config("${HYB_CONFIG_PATH}")
endif()

# Pass 2 applies one-off command-line overrides.
set(i 0)
while(i LESS argc)
    list(GET HYB_ARGS ${i} arg)
    if(arg STREQUAL "--help")
        message("HyRemote build entry point\n\nUsage: compile.cmd [options]\n\nConfiguration precedence: defaults < build.yml < command line\n\n  --config=FILE | --no-config\n  --mode=cpp|qml|generic|qpa|all|minimal\n  --integrations=cpp,qml,generic,qpa\n  --build-type=Release|Debug\n  --build-dir=DIR\n  --generator=NAME\n  --qt-prefix=PATH\n  --toolchain=FILE.cmake\n  --c-compiler=PATH --cxx-compiler=PATH\n  --tests | --no-tests\n  --run-tests | --no-run-tests\n  --examples | --no-examples\n  --test-exclude=REGEX --xvfb | --no-xvfb\n  --cmake=KEY=VALUE (repeatable)\n  --env=KEY=VALUE (repeatable)\n  --clean -v -jN --jobs=N --print-config")
        return()
    elseif(arg MATCHES "^--config=" OR arg STREQUAL "--no-config")
        # Already consumed in pass 1.
    elseif(arg STREQUAL "--config")
        math(EXPR i "${i}+1")
    elseif(arg STREQUAL "--mode" OR arg STREQUAL "--integrations" OR arg STREQUAL "--build-type"
           OR arg STREQUAL "--build-dir" OR arg STREQUAL "--generator" OR arg STREQUAL "--qt-prefix"
           OR arg STREQUAL "--toolchain" OR arg STREQUAL "--c-compiler" OR arg STREQUAL "--cxx-compiler"
           OR arg STREQUAL "--test-exclude" OR arg STREQUAL "--cmake" OR arg STREQUAL "--env"
           OR arg STREQUAL "--jobs")
        set(option_name "${arg}")
        math(EXPR i "${i}+1")
        if(i GREATER_EQUAL argc)
            message(FATAL_ERROR "${option_name} requires a value")
        endif()
        list(GET HYB_ARGS ${i} option_value)
        if(option_name STREQUAL "--mode")
            set(HYB_MODE "${option_value}")
            set(HYB_INTEGRATIONS "")
        elseif(option_name STREQUAL "--integrations")
            string(REPLACE "," ";" HYB_INTEGRATIONS "${option_value}")
            set(HYB_MODE "")
        elseif(option_name STREQUAL "--build-type")
            set(HYB_BUILD_TYPE "${option_value}")
        elseif(option_name STREQUAL "--build-dir")
            set(HYB_BUILD_DIR "${option_value}")
        elseif(option_name STREQUAL "--generator")
            set(HYB_GENERATOR "${option_value}")
        elseif(option_name STREQUAL "--qt-prefix")
            set(HYB_QT_PREFIX "${option_value}")
        elseif(option_name STREQUAL "--toolchain")
            set(HYB_TOOLCHAIN "${option_value}")
        elseif(option_name STREQUAL "--c-compiler")
            set(HYB_C_COMPILER "${option_value}")
        elseif(option_name STREQUAL "--cxx-compiler")
            set(HYB_CXX_COMPILER "${option_value}")
        elseif(option_name STREQUAL "--test-exclude")
            set(HYB_TESTS_EXCLUDE "${option_value}")
        elseif(option_name STREQUAL "--cmake")
            if(NOT option_value MATCHES "^([^=]+)=(.*)$")
                message(FATAL_ERROR "--cmake expects KEY=VALUE")
            endif()
            hyb_append_pair(HYB_CMAKE_CACHE_ENTRIES "${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}")
        elseif(option_name STREQUAL "--env")
            if(NOT option_value MATCHES "^([^=]+)=(.*)$")
                message(FATAL_ERROR "--env expects KEY=VALUE")
            endif()
            hyb_append_pair(HYB_ENV_ENTRIES "${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}")
        elseif(option_name STREQUAL "--jobs")
            if(NOT option_value MATCHES "^[1-9][0-9]*$")
                message(FATAL_ERROR "--jobs expects a positive integer")
            endif()
            set(HYB_JOBS "${option_value}")
        endif()
    elseif(arg MATCHES "^--mode=(.+)$")
        set(HYB_MODE "${CMAKE_MATCH_1}")
        set(HYB_INTEGRATIONS "")
    elseif(arg MATCHES "^--integrations=(.+)$")
        string(REPLACE "," ";" HYB_INTEGRATIONS "${CMAKE_MATCH_1}")
        set(HYB_MODE "")
    elseif(arg MATCHES "^--build-type=(.+)$")
        set(HYB_BUILD_TYPE "${CMAKE_MATCH_1}")
    elseif(arg MATCHES "^--build-dir=(.+)$")
        set(HYB_BUILD_DIR "${CMAKE_MATCH_1}")
    elseif(arg MATCHES "^--generator=(.+)$")
        set(HYB_GENERATOR "${CMAKE_MATCH_1}")
    elseif(arg MATCHES "^--qt-prefix=(.+)$")
        set(HYB_QT_PREFIX "${CMAKE_MATCH_1}")
    elseif(arg MATCHES "^--toolchain=(.+)$")
        set(HYB_TOOLCHAIN "${CMAKE_MATCH_1}")
    elseif(arg MATCHES "^--c-compiler=(.+)$")
        set(HYB_C_COMPILER "${CMAKE_MATCH_1}")
    elseif(arg MATCHES "^--cxx-compiler=(.+)$")
        set(HYB_CXX_COMPILER "${CMAKE_MATCH_1}")
    elseif(arg STREQUAL "--tests")
        set(HYB_TESTS_BUILD ON)
    elseif(arg STREQUAL "--no-tests")
        set(HYB_TESTS_BUILD OFF)
        set(HYB_TESTS_RUN OFF)
    elseif(arg STREQUAL "--run-tests")
        set(HYB_TESTS_BUILD ON)
        set(HYB_TESTS_RUN ON)
    elseif(arg STREQUAL "--no-run-tests")
        set(HYB_TESTS_RUN OFF)
    elseif(arg STREQUAL "--examples")
        set(HYB_EXAMPLES ON)
    elseif(arg STREQUAL "--no-examples")
        set(HYB_EXAMPLES OFF)
    elseif(arg MATCHES "^--test-exclude=(.*)$")
        set(HYB_TESTS_EXCLUDE "${CMAKE_MATCH_1}")
    elseif(arg STREQUAL "--xvfb")
        set(HYB_TESTS_XVFB ON)
    elseif(arg STREQUAL "--no-xvfb")
        set(HYB_TESTS_XVFB OFF)
    elseif(arg MATCHES "^--cmake=(.+)$")
        if(NOT CMAKE_MATCH_1 MATCHES "^([^=]+)=(.*)$")
            message(FATAL_ERROR "--cmake expects KEY=VALUE")
        endif()
        hyb_append_pair(HYB_CMAKE_CACHE_ENTRIES "${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}")
    elseif(arg MATCHES "^--env=(.+)$")
        if(NOT CMAKE_MATCH_1 MATCHES "^([^=]+)=(.*)$")
            message(FATAL_ERROR "--env expects KEY=VALUE")
        endif()
        hyb_append_pair(HYB_ENV_ENTRIES "${CMAKE_MATCH_1}" "${CMAKE_MATCH_2}")
    elseif(arg STREQUAL "--clean")
        set(HYB_CLEAN ON)
    elseif(arg STREQUAL "-v" OR arg STREQUAL "--verbose")
        set(HYB_VERBOSE ON)
    elseif(arg STREQUAL "--print-config")
        set(HYB_PRINT_CONFIG ON)
    elseif(arg MATCHES "^-j([1-9][0-9]*)$")
        set(HYB_JOBS "${CMAKE_MATCH_1}")
    elseif(arg MATCHES "^--jobs=([1-9][0-9]*)$")
        set(HYB_JOBS "${CMAKE_MATCH_1}")
    else()
        message(FATAL_ERROR "Unknown build option '${arg}'. Use --help.")
    endif()
    math(EXPR i "${i}+1")
endwhile()

if(HYB_TESTS_RUN AND NOT HYB_TESTS_BUILD)
    set(HYB_TESTS_BUILD ON)
endif()

# C++ is the shared runtime's baseline API. Optional frontends only add payloads over that same runtime.
if(HYB_INTEGRATIONS STREQUAL "")
    string(TOLOWER "${HYB_MODE}" mode_l)
    if(mode_l STREQUAL "cpp")
        set(HYB_INTEGRATIONS cpp)
    elseif(mode_l STREQUAL "qml")
        set(HYB_INTEGRATIONS cpp qml)
    elseif(mode_l STREQUAL "generic")
        set(HYB_INTEGRATIONS cpp generic)
    elseif(mode_l STREQUAL "qpa")
        set(HYB_INTEGRATIONS cpp qpa)
    elseif(mode_l STREQUAL "all")
        set(HYB_INTEGRATIONS cpp qml generic qpa)
    elseif(mode_l STREQUAL "minimal")
        set(HYB_INTEGRATIONS cpp)
        set(HYB_TESTS_BUILD OFF)
        set(HYB_TESTS_RUN OFF)
        set(HYB_EXAMPLES OFF)
    else()
        message(FATAL_ERROR "Unknown mode '${HYB_MODE}'")
    endif()
endif()

set(valid_integrations cpp qml generic qpa)
set(normalized_integrations "")
foreach(item IN LISTS HYB_INTEGRATIONS)
    string(STRIP "${item}" item)
    string(TOLOWER "${item}" item)
    if(NOT item IN_LIST valid_integrations)
        message(FATAL_ERROR "Unknown integration '${item}'; expected cpp, qml, generic or qpa")
    endif()
    if(NOT item IN_LIST normalized_integrations)
        list(APPEND normalized_integrations "${item}")
    endif()
endforeach()
if(NOT cpp IN_LIST normalized_integrations)
    list(PREPEND normalized_integrations cpp)
endif()
set(HYB_INTEGRATIONS "${normalized_integrations}")

set(HYB_QML OFF)
set(HYB_GENERIC OFF)
set(HYB_QPA OFF)
if(qml IN_LIST HYB_INTEGRATIONS)
    set(HYB_QML ON)
endif()
if(generic IN_LIST HYB_INTEGRATIONS)
    set(HYB_GENERIC ON)
endif()
if(qpa IN_LIST HYB_INTEGRATIONS)
    set(HYB_QPA ON)
endif()

function(hyb_resolve_path variable must_exist description)
    set(value "${${variable}}")
    if(value STREQUAL "")
        return()
    endif()
    if(NOT IS_ABSOLUTE "${value}" AND value MATCHES "[/\\\\]")
        set(value "${HYREMOTE_SOURCE_DIR}/${value}")
    endif()
    if(IS_ABSOLUTE "${value}")
        cmake_path(NORMAL_PATH value)
    endif()
    if(must_exist AND value MATCHES "[/\\\\]" AND NOT EXISTS "${value}")
        message(FATAL_ERROR "${description} does not exist: ${value}")
    endif()
    set(${variable} "${value}" PARENT_SCOPE)
endfunction()

hyb_resolve_path(HYB_QT_PREFIX TRUE "Qt prefix")
hyb_resolve_path(HYB_TOOLCHAIN TRUE "Toolchain file")
hyb_resolve_path(HYB_C_COMPILER TRUE "C compiler")
hyb_resolve_path(HYB_CXX_COMPILER TRUE "C++ compiler")

if(NOT IS_ABSOLUTE "${HYB_BUILD_DIR}")
    set(HYB_BUILD_DIR "${HYREMOTE_SOURCE_DIR}/${HYB_BUILD_DIR}")
endif()
cmake_path(NORMAL_PATH HYB_BUILD_DIR)

string(JOIN "," HYB_INTEGRATIONS_TEXT ${HYB_INTEGRATIONS})
message(STATUS "HyRemote build configuration")
message(STATUS "  config file  : ${HYB_CONFIG_PATH}")
message(STATUS "  integrations : ${HYB_INTEGRATIONS_TEXT}")
message(STATUS "  build type   : ${HYB_BUILD_TYPE}")
message(STATUS "  build dir    : ${HYB_BUILD_DIR}")
message(STATUS "  generator    : ${HYB_GENERATOR}")
message(STATUS "  jobs         : ${HYB_JOBS}")
message(STATUS "  Qt prefix    : ${HYB_QT_PREFIX}")
message(STATUS "  toolchain    : ${HYB_TOOLCHAIN}")
message(STATUS "  C compiler   : ${HYB_C_COMPILER}")
message(STATUS "  C++ compiler : ${HYB_CXX_COMPILER}")
message(STATUS "  tests        : build=${HYB_TESTS_BUILD}, run=${HYB_TESTS_RUN}, xvfb=${HYB_TESTS_XVFB}")
message(STATUS "  examples     : ${HYB_EXAMPLES}")
message(STATUS "  cmake cache  : ${HYB_CMAKE_CACHE_ENTRIES}")
message(STATUS "  environment  : ${HYB_ENV_ENTRIES}")

if(HYB_PRINT_CONFIG)
    return()
endif()

if(HYB_CLEAN AND EXISTS "${HYB_BUILD_DIR}")
    file(REMOVE_RECURSE "${HYB_BUILD_DIR}")
endif()
file(MAKE_DIRECTORY "${HYB_BUILD_DIR}")

# Prevent one build tree from silently mixing compilers, Qt kits or integration payload identities.
set(identity
    "generator=${HYB_GENERATOR}\nqt=${HYB_QT_PREFIX}\ntoolchain=${HYB_TOOLCHAIN}\nc=${HYB_C_COMPILER}\ncxx=${HYB_CXX_COMPILER}\nintegrations=${HYB_INTEGRATIONS_TEXT}\n")
set(identity_file "${HYB_BUILD_DIR}/.hyremote-build-identity")
if(EXISTS "${identity_file}")
    file(READ "${identity_file}" previous_identity)
    if(NOT previous_identity STREQUAL identity)
        message(FATAL_ERROR
            "The existing build directory has a different compiler/Qt/integration identity. "
            "Run compile.cmd --clean once after changing build.yml or these command-line options.")
    endif()
endif()
file(WRITE "${identity_file}" "${identity}")

set(configure_cmd
    "${CMAKE_COMMAND}"
    -S "${HYREMOTE_SOURCE_DIR}"
    -B "${HYB_BUILD_DIR}"
    -G "${HYB_GENERATOR}"
    "-DCMAKE_BUILD_TYPE=${HYB_BUILD_TYPE}"
    "-DHYREMOTE_BUILD_TESTS=${HYB_TESTS_BUILD}"
    "-DHYREMOTE_BUILD_EXAMPLES=${HYB_EXAMPLES}"
    "-DHYREMOTE_BUILD_QML_API=${HYB_QML}"
    "-DHYREMOTE_WITH_GENERIC_PLUGIN=${HYB_GENERIC}"
    "-DHYREMOTE_WITH_QPA_PROXY=${HYB_QPA}")
if(NOT HYB_QT_PREFIX STREQUAL "")
    list(APPEND configure_cmd "-DCMAKE_PREFIX_PATH=${HYB_QT_PREFIX}")
endif()
if(NOT HYB_TOOLCHAIN STREQUAL "")
    list(APPEND configure_cmd "-DCMAKE_TOOLCHAIN_FILE=${HYB_TOOLCHAIN}")
endif()
if(NOT HYB_C_COMPILER STREQUAL "")
    list(APPEND configure_cmd "-DCMAKE_C_COMPILER=${HYB_C_COMPILER}")
endif()
if(NOT HYB_CXX_COMPILER STREQUAL "")
    list(APPEND configure_cmd "-DCMAKE_CXX_COMPILER=${HYB_CXX_COMPILER}")
endif()
foreach(entry IN LISTS HYB_CMAKE_CACHE_ENTRIES)
    list(APPEND configure_cmd "-D${entry}")
endforeach()

set(env_cmd "${CMAKE_COMMAND}" -E env)
foreach(entry IN LISTS HYB_ENV_ENTRIES)
    list(APPEND env_cmd "${entry}")
endforeach()

set(configure_log "${HYB_BUILD_DIR}/configure.log")
if(HYB_VERBOSE)
    execute_process(COMMAND ${env_cmd} ${configure_cmd} RESULT_VARIABLE rc)
else()
    execute_process(
        COMMAND ${env_cmd} ${configure_cmd}
        RESULT_VARIABLE rc
        OUTPUT_FILE "${configure_log}"
        ERROR_FILE "${configure_log}")
endif()
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Configure failed (${rc}). See ${configure_log}")
endif()

set(build_cmd "${CMAKE_COMMAND}" --build "${HYB_BUILD_DIR}")
if(NOT HYB_JOBS STREQUAL "")
    list(APPEND build_cmd --parallel "${HYB_JOBS}")
else()
    list(APPEND build_cmd --parallel)
endif()
set(build_log "${HYB_BUILD_DIR}/build.log")
if(HYB_VERBOSE)
    execute_process(COMMAND ${env_cmd} ${build_cmd} RESULT_VARIABLE rc)
else()
    execute_process(
        COMMAND ${env_cmd} ${build_cmd}
        RESULT_VARIABLE rc
        OUTPUT_FILE "${build_log}"
        ERROR_FILE "${build_log}")
endif()
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Build failed (${rc}). See ${build_log}")
endif()

if(HYB_TESTS_RUN)
    set(test_env ${HYB_ENV_ENTRIES})
    if(WIN32)
        file(GLOB_RECURSE runtime_candidates LIST_DIRECTORIES FALSE "${HYB_BUILD_DIR}/HyRemoteRemoteAccess.dll")
        if(runtime_candidates)
            list(GET runtime_candidates 0 runtime_file)
            get_filename_component(runtime_dir "${runtime_file}" DIRECTORY)
        else()
            set(runtime_dir "")
        endif()
        set(test_path "$ENV{PATH}")
        if(NOT HYB_QT_PREFIX STREQUAL "")
            string(PREPEND test_path "${HYB_QT_PREFIX}/bin;")
        endif()
        if(NOT runtime_dir STREQUAL "")
            string(PREPEND test_path "${runtime_dir};")
        endif()
        list(APPEND test_env "PATH=${test_path}")
    elseif(UNIX)
        file(GLOB_RECURSE runtime_candidates LIST_DIRECTORIES FALSE "${HYB_BUILD_DIR}/libHyRemoteRemoteAccess.so")
        if(runtime_candidates)
            list(GET runtime_candidates 0 runtime_file)
            get_filename_component(runtime_dir "${runtime_file}" DIRECTORY)
        else()
            set(runtime_dir "")
        endif()
        set(test_ld "$ENV{LD_LIBRARY_PATH}")
        if(NOT HYB_QT_PREFIX STREQUAL "")
            string(PREPEND test_ld "${HYB_QT_PREFIX}/lib:")
        endif()
        if(NOT runtime_dir STREQUAL "")
            string(PREPEND test_ld "${runtime_dir}:")
        endif()
        list(APPEND test_env "LD_LIBRARY_PATH=${test_ld}")
    endif()

    set(ctest_cmd "${CMAKE_CTEST_COMMAND}" --test-dir "${HYB_BUILD_DIR}" --output-on-failure)
    if(NOT HYB_TESTS_PARALLEL STREQUAL "")
        list(APPEND ctest_cmd --parallel "${HYB_TESTS_PARALLEL}")
    elseif(NOT HYB_JOBS STREQUAL "")
        list(APPEND ctest_cmd --parallel "${HYB_JOBS}")
    endif()
    if(NOT HYB_TESTS_EXCLUDE STREQUAL "")
        list(APPEND ctest_cmd -E "${HYB_TESTS_EXCLUDE}")
    endif()

    if(HYB_TESTS_XVFB AND UNIX AND NOT APPLE)
        find_program(XVFB_RUN xvfb-run)
        if(NOT XVFB_RUN)
            message(FATAL_ERROR "tests.xvfb=true but xvfb-run was not found")
        endif()
        set(run_test_cmd "${XVFB_RUN}" -a ${ctest_cmd})
    else()
        set(run_test_cmd ${ctest_cmd})
    endif()

    set(test_log "${HYB_BUILD_DIR}/test.log")
    if(HYB_VERBOSE)
        execute_process(
            COMMAND "${CMAKE_COMMAND}" -E env ${test_env} ${run_test_cmd}
            RESULT_VARIABLE rc)
    else()
        execute_process(
            COMMAND "${CMAKE_COMMAND}" -E env ${test_env} ${run_test_cmd}
            RESULT_VARIABLE rc
            OUTPUT_FILE "${test_log}"
            ERROR_FILE "${test_log}")
    endif()
    if(NOT rc EQUAL 0)
        message(FATAL_ERROR "Tests failed (${rc}). See ${test_log}")
    endif()
endif()

message(STATUS "HyRemote build succeeded")
